apiVersion: v1
kind: Service
metadata:
  name: sonarqube-service
  namespace: default
spec:
  ports:
    - port: 9442
      targetPort: 9000
      protocol: TCP
  type: NodePort
  selector:
    app: sonarqube
  type: LoadBalancer
  sessionAffinity: None
  externalTrafficPolicy: Cluster
status:
  loadBalancer:
    ingress:
      - hostname: localhost