apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: claimnumber-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas.replicaCount }}
  template:
    metadata:
      labels:
        app: claimnumber
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: claimnumber
        ports:
        - containerPort: {{ .Values.service.internalport }}
        readinessProbe:
          httpGet:
            path: /claimnumber/healthcheck/
            port: {{ .Values.service.internalport }}
          initialDelaySeconds: 20
          periodSeconds: 20
          failureThreshold: 7
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
