apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: claimnumber-db-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas.replicaCount }}
  template:
    metadata:
      labels:
        app: claim-db
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: claim-db
        ports:
        - containerPort: {{ .Values.service.internalport }}
        env:
          - name: POSTGRES_DB
            value: claimnumber
          - name: POSTGRES_USER
            value: user1
          - name: POSTGRES_PASSWORD
            value: passord        
        volumeMounts:
         - mountPath: "/var/lib/postgresql/data"
           name: {{ .Values.mounts.name }}
      volumes:
        - name: {{ .Values.mounts.name }}
          hostPath:
            path: {{ .Values.mounts.path }}
            type: DirectoryOrCreate
