apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: claimnumber-db-deployment
  namespace: {{ .Values.metadata.namespace }}
spec:
  replicas: {{ .Values.replicas.replicaCount }}
  template:
    metadata:
      labels:
        app: claim-db
    spec:
      containers:
      - image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: Always
        name: claim-db
        ports:
        - containerPort: {{ .Values.service.internalport }}
        volumeMounts:
         - mountPath: /var/lib/postgresql/data
           name: claim-db-dev
      volumes:
        - name: claim-db-dev
          hostPath:
            path: {{ .Values.mounts.path }}
            type: DirectoryOrCreate
